name: Applicability of Fedora RPM patches on upstream LLVM

on:
  schedule:
    # Every weekday at 00:00
    # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
    - cron:  '0 0 * * 1-5'

  # Uncomment to be able to trigger the workflow manually
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
  workflow_dispatch: {}
    
jobs:
  apply-patches:
    runs-on: [ubuntu-latest]
    strategy:
      # Don't cancel any in-progress jobs if any matrix job fails
      # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      # Always test the latest LLVM (main branch) on the latest Fedora (rawhide) branch
      matrix:
        llvm-branch: [main, release/11.x, release/10.x]
        fedora-rpm-branch: [rawhide, f34, f33, f32]
        rpm: [llvm, clang, lld, compiler-rt, libcxx, libcxxabi, libomp, libunwind, lldb, llvm-test-suite, polly]
        exclude:
          - llvm-branch: main
            fedora-rpm-branch: f34
          - llvm-branch: main
            fedora-rpm-branch: f33
          - llvm-branch: main
            fedora-rpm-branch: f32

          - llvm-branch: release/11.x
            fedora-rpm-branch: rawhide
          - llvm-branch: release/11.x
            fedora-rpm-branch: f32

          - llvm-branch: release/10.x
            fedora-rpm-branch: rawhide
          - llvm-branch: release/10.x
            fedora-rpm-branch: f34
          - llvm-branch: release/10.x
            fedora-rpm-branch: f33
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15' # The Go version to download (if necessary) and use.

      # https://github.com/actions/checkout
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: main
          ref: main

      - name: Checkout LLVM monorepo
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: ${{ matrix.llvm-branch }}

      - name: "Apply Fedora ${{ matrix.fedora-rpm-branch }} patches of the ${{ matrix.rpm }} RPMs to the LLVM (branch=${{ matrix.llvm-branch}})"
        if: always()
        shell: bash
        run: |
          git clone --depth 1 -b ${{ matrix.fedora-rpm-branch }} https://src.fedoraproject.org/rpms/${{ matrix.rpm }}.git rpm-${{ matrix.rpm }}
          go run main/main.go rpm-${{ matrix.rpm }}/${{ matrix.rpm }}.spec llvm-project/${{ matrix.rpm }}

      - name: Google Chat Notification for llvm package
        if: failure() && ${{ matrix.llvm-branch == 'main' && matrix.fedora-rpm-branch == 'rawhide' }}
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: The Fedora ${{ matrix.fedora-rpm-branch }} "${{ matrix.rpm }}" RPMs contain patches that can not be applied to upstream LLVM (branch=${{ matrix.llvm-branch}})
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}