name: fedora-rpm-patches-on-upstream-llvm

on:
  schedule:
    # Every 6 minute(s)
    # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
    - cron:  '*/6 * * * *'

  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events
  workflow_dispatch: {}
    
jobs:
  apply-patches:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        llvm-branch: [main, release/12.x, release/11.x, release/10.x]
        fedora-rpm-branch: [rawhide, f34, f33, f32]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14' # The Go version to download (if necessary) and use.

      # https://github.com/actions/checkout
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: main
          ref: main

      - name: Checkout LLVM monorepo
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: ${{ matrix.llvm-branch }}

      - name: Check if all LLVM patches can be applied to the latest LLVM monorepo
        shell: bash
        run: |
          git clone --depth 1 -b ${{ matrix.fedora-rpm-branch }} https://src.fedoraproject.org/rpms/llvm.git rpm-llvm
          go run main/main.go rpm-llvm/llvm.spec llvm-project/llvm
          

      - name: Check if all clang patches can be applied to the latest LLVM monorepo
        shell: bash
        run: |
          git clone --depth 1 -b ${{ matrix.fedora-rpm-branch }} https://src.fedoraproject.org/rpms/clang.git rpm-clang
          go run main/main.go rpm-clang/clang.spec llvm-project/clang

      - name: Check if all lldf patches can be applied to the latest LLVM monorepo
        shell: bash
        run: |
          git clone --depth 1 -b ${{ matrix.fedora-rpm-branch }} https://src.fedoraproject.org/rpms/lld.git rpm-lld
          go run main/main.go rpm-lld/lld.spec llvm-project/lld
      
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Fedora RPM patches applicability on upstream LLVM
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
          info: Enter useful text here :)
        if: always()