name: fedora-rawhide-rpm-patches-on-upstream-llvm

on:
  schedule:
    #
    #          ┌───────────── minute (0 - 59)
    #          │ ┌───────────── hour (0 - 23)
    #          │ │ ┌───────────── day of the month (1 - 31)
    #          │ │ │ ┌───────────── month (1 - 12)
    #          │ │ │ │ ┌───────────── day of the week (0 - 6)
    #          │ │ │ │ │                                   
    #          │ │ │ │ │
    #          │ │ │ │ │
    #          * * * * *
    # Run every day at 16 o'clock
    # - cron: "  * 16 * * *"
    # At the end of every day
    # 0 0 * * *
    # Every 5 minutes
    - cron: "*/5 * * * *"
    
jobs:
  apply-patches:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14' # The Go version to download (if necessary) and use.

      # https://github.com/actions/checkout
      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: main
          ref: main

      - name: Checkout RPM repo for llvm
        uses: actions/checkout@v2
        with:
          repository: https://src.fedoraproject.org/rpms/llvm.git
          path: rpm-llvm
          ref: rawhide

      - name: Checkout RPM repo for clang
        uses: actions/checkout@v2
        with:
          repository: https://src.fedoraproject.org/rpms/clang.git
          path: rpm-clang
          ref: rawhide

      - name: Checkout RPM repo for lld
        uses: actions/checkout@v2
        with:
          repository: https://src.fedoraproject.org/rpms/lld.git
          path: rpm-lld
          ref: rawhide

      - name: Checkout LLVM monorepo
        uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
          path: llvm-project
          ref: main

      - name: Check if all LLVM patches can be applied to the latest LLVM monorepo
        shell: bash
        run: |
          go run main/main.go rpm-llvm/llvm.spec llvm-project/llvm
          

      - name: Check if all clang patches can be applied to the latest LLVM monorepo
        shell: bash
        run: |
          go run main/main.go rpm-clang/clang.spec llvm-project/clang

      - name: Check if all lldf patches can be applied to the latest LLVM monorepo
        shell: bash
        run: |
          go run main/main.go rpm-lld/lld.spec llvm-project/lld